esphome:
  name: irk-capture-example
  friendly_name: IRK Capture Example

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble:
  id: ble_core
  name: "IRK Capture"
  io_capability: none
  auth_req_mode: sc_bond
  max_connections: 1

esp32_ble_server:
  id: ble_server
  manufacturer: "ESPHome"
  model: "IRK Capture"
  appearance: 0x4142
  max_clients: 1

external_components:
  - source:
       type: git
       url: https://github.com/Yiivgeny/esphome-irk-capture
       ref: main
    components: [irk_capture]

text_sensor:
  - platform: template
    name: "Last IRK"
    id: last_irk_text
    icon: "mdi:key-wireless"
    update_interval: never

irk_capture:
  id: irk_capture_component
  ble_id: ble_core
  ble_server_id: ble_server
  enroll_switch:
    id: ble_enroll_switch
    name: "BLE Enroll"
  on_irk:
    then:
      - text_sensor.template.publish:
          id: last_irk_text
          state: !lambda "return irk;"
      - logger.log:
          format: "Discovered IRK %s for %s"
          args:
            - irk.c_str()
            - address.c_str()
