esphome:
  name: irk-capture-dev
  friendly_name: IRK Capture Dev

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: local
      path: ../components
    components: [irk_capture]

esp32_ble:
  id: ble_core
  io_capability: none
  auth_req_mode: sc_bond
  max_connections: 1

esp32_ble_server:
  id: ble_server
  manufacturer: "ESPHome"
  model: "IRK Capture"
  appearance: 0x4142
  max_clients: 1

irk_capture:
  id: irk_capture_component
  ble_id: ble_core
  ble_server_id: ble_server
  visible_switch:
    name: "BLE Visible"
  enroll_switch:
    name: "BLE Enroll"
  on_irk:
    then:
      - logger.log:
          format: "Discovered IRK %s for %s"
          args:
            - irk.c_str()
            - address.c_str()
